baseurl: /
languageCode: en-us
title: Drew Howell
theme: "cactus"
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: about
      url: /about/
      weight: 5
    - name: intro to DS
      url: /tags/r-markdown/
      weight: 2
    - name: resume
      url: /resume/
      weight: 3
    - name: GitHub
      url: https://github.com/drehow
      weight: 4
    
params:
  mainSections:
    - post
  intro: true
  headline: Drew Howell
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
