baseurl: /
languageCode: en-us
title: Drew Howell
theme: "cactus"
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: home
      url: /
      weight: 1
#    - name: about
#      url: /about/
#      weight: 5
    - name: teaching
      url: /tags/r-markdown/
      weight: 2
    - name: resume
      url: /resume/
      weight: 4
    - name: projects
      url: https://github.com/drehow
      weight: 3
    - name: tags
      url: /tags/
      weight: 5
    
params:
  description: Welcome! This is a personal site where I keep the articles and web apps that I use to teach my class, as well as some other pet projects. Most of the material is related to data science. Feel free to browse!
  mainSections:
    - post
  intro: true
  headline: Drew Howell
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
  colortheme: "dark" # dark, light, white, or classic
  showAllPostsOnHomePage: false
  postsOnHomePage: 7
  tagsOverview: true

